# Site settings
title: binweb.tech
description: Jasa pembuatan website, SEO & CCTV
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: binweb.tech
user_description: Kami adalah spesialis dalam pengembangan website responsif, pembuatan aplikasi web yang disesuaikan, dan solusi keamanan CCTV.
user_title: Solusi website & CCTV
email: binwebtech@gmail.com
# twitter_username: lorem_ipsum
instagram_username: binweb.tech
facebook_username: aden.fribadi
linkedin_username: aden-pribadi
github_username:  adenpribadi
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

