# Site settings
title: Jasa Pembuatan Website di Cikarang, Bekasi | binweb.tech
description: Optimalkan bisnis Anda dengan Jasa Pembuatan Website, Layanan SEO, dan Instalasi CCTV di Cikarang. Solusi lengkap untuk pertumbuhan bisnis Anda.
keywords: jasa pembuatan website cikarang, jasa SEO cikarang, jasa SEO Website cikarang, jasa pasang cctv cikarang, jasa pemasangan cctv di cikarang
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: "https://binweb.tech" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap

# User settings
username: binweb.tech
user_description: Kami adalah spesialis dalam pengembangan website responsif, pembuatan aplikasi web yang disesuaikan, dan solusi keamanan CCTV.
user_title: Solusi website & CCTV
email: binwebtech@gmail.com
# twitter_username: lorem_ipsum
instagram_username: binweb.tech
facebook_username: aden.fribadi
linkedin_username: binweb-tech-52445b291
github_username:  adenpribadi
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

